version: "3.7"

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - .:/var/www:delegated
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:delegated
    ports:
      - "80:80"
    depends_on:
      - php-fpm

  php-fpm:
    build: docker/php-fpm
    container_name: php-fpm
    volumes:
      - .:/var/www:delegated
      - ./docker/php-fpm/php.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini:delegated